repos:
  #- repo: local
  #  hooks:
  #    - id: trufflehog
  #      name: TruffleHog
  #      description: Detect secrets in your data.
  #      entry: sh -c "docker run --rm -v $PWD:/pwd trufflesecurity/trufflehog:latest git file:///pwd --since-commit HEAD --results=verified,unknown --fail"
  #      language: system
  #      stages: ["pre-commit", "pre-push"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.5
    hooks:
        - id: clang-format
          files: .(c|h|cpp|hpp)$
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
        - id: cmake-format
          files: (\.cmake|CMakeLists.txt)(.in)?$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
    - id: ruff-check
    - id: ruff-format
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.5.0
    hooks:
    - id: sqlfluff-lint
      args: ["--dialect", "postgres"]
    - id: sqlfluff-fix
      args: ["--dialect", "postgres"]
