components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: &blocking_num_workers 1
    default_task_processor: main-task-processor
    components:
        http-client:
            fs-task-processor: fs-task-processor
        secdist:
        default-secdist-provider:
            missing-ok: false
            config: /home/noofva/work/webshot/secrets/secdist.json
            format: json
        webshot-config:
            query-part-length-max: 32768
            s3-bucket: webshot
            s3-endpoint: 'http://localhost:8333'
            s3-region: 'local'
            public-base-url: 'http://localhost:8333/webshot'
            s3-timeout-ms: 30000
        dns-client:
            fs-task-processor: fs-task-processor
        testsuite-support:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard
        webshot-handler:
            path: /v1/webshot
            method: GET,POST
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: &max-data-per-request: 65536
        webshots-by-prefix:
            path: /v1/webshot/prefix
            method: GET
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-disallow-and-purge:
            path: /v1/disallow-and-purge
            method: POST
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-by-id:
            path: /v1/webshot/{uuid}
            method: GET
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-crud:
            webshots-page-max: 2
            crawl-concurrency: *blocking_num_workers
            webshots-per-link-max: 2
            webshots-links-per-page-max: 10
            crawler-network: 'crawler_net'
            crawler-image: 'webrecorder/browsertrix-crawler'
            crawler-collection-name: 'webshot'
            crawler-workers: 1
            crawler-page-load-timeout-sec: 10
            crawler-post-load-delay-sec: 1
            crawler-net-idle-wait-sec: 0
            crawler-page-extra-delay-sec: 3
            crawler-behavior-timeout-sec: 1
            crawler-overhead-timeout-sec: 45
            purge-job-timeout-sec: 300
            crawler-lang: 'en'
            crawler-scope-type: 'page-spa'
        webshot-meta-db:
            dbconnection: 'postgresql://postgres@localhost:5432'
            blocking_task_processor: fs-task-processor
        denylist-db:
            dbconnection: 'postgresql://postgres@localhost:5433'
            blocking_task_processor: fs-task-processor
        webshot-denylist:
