components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        fs-task-processor:
            worker_threads: &blocking_num_workers 1
    default_task_processor: main-task-processor
    components:
        http-client:
            fs-task-processor: fs-task-processor
        secdist:
        default-secdist-provider:
            missing-ok: true
            inline:
                s3_credentials: {}
        webshot-config:
            query-part-length-max: 1024
        dns-client:
            fs-task-processor: fs-task-processor
        testsuite-support:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard
        webshots-by-prefix:
            path: /v1/webshot
            method: GET
            task_processor: main-task-processor
        webshot-exact:
            path: /v1/webshot/exact
            method: GET
            task_processor: main-task-processor
        webshot-handler:
            path: /v1/webshot
            method: POST
            task_processor: main-task-processor
        webshot-by-id:
            path: /v1/webshot/{uuid}
            method: GET
            task_processor: main-task-processor
        webshot-crud:
            webshots-page-max: 2
            crawl-concurrency: *blocking_num_workers
            webshots-per-link-max: 2
            webshots-links-per-page-max: 10
            crawler-network: 'crawler_net'
            storage-mode: s3
            s3-bucket: webshot
            s3-endpoint: 'http://localhost:8333'
            s3-region: 'local'
            public-base-url: 'http://localhost:8333/webshot'
            s3-timeout-ms: 10000
        webshot-meta-db:
            dbconnection: 'postgresql://postgres@localhost:5432'
            blocking_task_processor: fs-task-processor
        denylist-db:
            dbconnection: 'postgresql://postgres@localhost:5433'
            blocking_task_processor: fs-task-processor
        webshot-denylist:
            # S3 settings to allow purges (mirror of crud)
            s3-bucket: webshot
            s3-endpoint: 'http://localhost:8333'
            s3-region: 'local'
            s3-timeout-ms: 10000
