name: ci
on:
  push:
  pull_request:
env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    extra-substituters = ${{ secrets.HARMONIA_SUBSTITUTER }} https://devenv.cachix.org
    extra-trusted-public-keys = ${{ secrets.HARMONIA_PUBLIC_KEY }} devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
defaults:
  run:
    shell: bash
jobs:
  test-san:
    name: build, test
    runs-on: nixos-nix
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Build, test
        run: |
          set -euo pipefail
          bash .forgejo/devenv_ci.sh shell -- podman pull docker.io/webrecorder/browsertrix-crawler:latest@sha256:35f863bdd26154fbcb6c79badc2d2ca7a1385e45df55523ed240b728acbf7582
          bash .forgejo/devenv_ci.sh tasks run webshot:buildSan
          bash .forgejo/devenv_ci.sh tasks run webshot:infraDevUp
          timeout --signal=TERM --kill-after=30s 30m bash .forgejo/devenv_ci.sh tasks run webshot:testSan
      - name: Cleanup infra
        if: always()
        run: |
          set -euo pipefail
          timeout --signal=TERM --kill-after=30s 5m bash .forgejo/devenv_ci.sh tasks run webshot:infraDevDown || true
