name: ci
on:
  push:
  pull_request:
env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    extra-substituters = ${{ secrets.HARMONIA_SUBSTITUTER }} https://devenv.cachix.org
    extra-trusted-public-keys = ${{ secrets.HARMONIA_PUBLIC_KEY }} devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
defaults:
  run:
    shell: bash
jobs:
  test-san:
    name: build, test
    runs-on: nixos-nix
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: Build, test
        run: |
          bash .forgejo/devenv_ci.sh tasks run webshot:devBuild
          bash .forgejo/devenv_ci.sh tasks run webshot:devTest
      - name: Cleanup infra
        if: always()
        run: |
          set -euo pipefail
          bash .forgejo/devenv_ci.sh tasks run webshot:devDown || true
