version: "3.9"
services:
  egress-proxy:
    container_name: egress-proxy
    image: docker.io/ubuntu/squid:6.6-24.04_beta@sha256:6a097f68bae708cedbabd6188d68c7e2e7a38cedd05a176e1cc0ba29e3bbe029
    restart: on-failure
    networks:
      - egress_net
      - crawler_net
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./squid.mode.prodlike.conf:/etc/squid/squid.mode.conf:ro
      - ./healthcheck_squid.sh:/usr/local/bin/healthcheck_squid.sh:ro
    healthcheck:
      test: ["CMD", "/bin/sh", "/usr/local/bin/healthcheck_squid.sh"]
      interval: disable
      timeout: 2s
      retries: 60
  servicedb:
    container_name: servicedb
    image: docker.io/postgres:18.1-trixie@sha256:5ec39c188013123927f30a006987c6b0e20f3ef2b54b140dfa96dac6844d883f
    restart: on-failure
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../../sql/schema:/docker-entrypoint-initdb.d/schema:ro
      - ../../containers/service-db-init-multi-db.sh:/docker-entrypoint-initdb.d/10-service-db-init-multi-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U postgres"]
      interval: disable
      timeout: 2s
      retries: 60
  webshot-test-target:
    container_name: webshot-test-target
    image: docker.io/nginx:alpine@sha256:b3c656d55d7ad751196f21b7fd2e8d4da9cb430e32f646adcf92441b72f82b14
    restart: on-failure
    networks:
      crawler_net:
        aliases:
          - test-target
    volumes:
      - ../../containers/nginx-test.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  crawler_net:
    name: crawler_net
    external: true
  egress_net:
    name: egress_net
    external: true
