s3_bucket: webshot
s3_endpoint: "https://storage.yandexcloud.net/"
s3_region: "ru-central1"
public_base_url: "https://storage.yandexcloud.net/webshot"
s3_use_sts: true
s3_credentials_endpoint: 'https://sts.yandexcloud.net/'
s3_credentials_duration_sec: 3600
s3_credentials_refresh_margin_sec: 300
s3_credentials_refresh_retry_sec: 60
pg_webshot_meta_dsn: "postgresql://postgres@localhost:5432/capture_meta_db"
pg_shared_state_dsn: "postgresql://postgres@localhost:5432/shared_state_db"
crawler_size_limit_mib: 50
crawler_page_load_timeout_sec: 10
crawler_post_load_delay_sec: 1
crawler_net_idle_wait_sec: 0
crawler_page_extra_delay_sec: 3
crawler_behavior_timeout_sec: 1
crawler_container_timeout_sec: 15
crawler_overhead_timeout_sec: 45
crawler_proxy_server: "http://egress_proxy:3128"
link_cooldown_sec: 0
