s3_bucket: webshot
s3_endpoint: "http://localhost:8333"
s3_region: "us-east-1"
public_base_url: "http://localhost:8333/webshot"
s3_use_sts: false
pg_webshot_meta_dsn: "postgresql://postgres@localhost:5432/capture_meta_db"
pg_shared_state_dsn: "postgresql://postgres@localhost:5432/shared_state_db"
crawler_size_limit_mib: 50
crawler_page_load_timeout_sec: 10
crawler_post_load_delay_sec: 1
crawler_net_idle_wait_sec: 0
crawler_page_extra_delay_sec: 0
crawler_behavior_timeout_sec: 1
crawler_container_timeout_sec: 15
crawler_overhead_timeout_sec: 45
crawler_proxy_server: "http://egress_proxy:3128"
link_cooldown_sec: 0
secdist_path: secret/test_secdist.json
