s3_bucket: webshot
s3_endpoint: "https://storage.yandexcloud.net/"
s3_region: "ru-central1"
public_base_url: "https://storage.yandexcloud.net/webshot"
s3_use_sts: true
s3-credentials-endpoint: 'https://sts.yandexcloud.net/'
s3-credentials-duration-sec: 3600
s3-credentials-refresh-margin-sec: 300
s3-credentials-refresh-retry-sec: 60
pg_webshot_meta_dsn: "postgresql://postgres@localhost:5432/capture_meta_db"
pg_shared_state_dsn: "postgresql://postgres@localhost:5432/shared_state_db"
crawler_size_limit_mib: 50
crawler-page-load-timeout-sec: 10
crawler-post-load-delay-sec: 1
crawler-net-idle-wait-sec: 0
crawler-page-extra-delay-sec: 3
crawler-behavior-timeout-sec: 1
crawler-container-timeout-sec: 15
crawler-overhead-timeout-sec: 45
link-cooldown-sec: 0
