components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
        crawling-task-processor:
            worker_threads: 4
            thread_name: crawling-task-processor-worker
        fs-task-processor:
            worker_threads: &blocking_num_workers 4
    default_task_processor: main-task-processor
    components:
        http-client:
            fs-task-processor: fs-task-processor
        secdist:
        default-secdist-provider:
            missing-ok: true
            format: json
            environment-secrets-key: WEBSHOT_SECRETS_KEY
        dynamic-config:
            defaults:
                USERVER_RPS_CCONTROL_ENABLED: true
        webshot-config:
            query-part-length-max: 32768
            s3-bucket: $s3_bucket
            s3-endpoint: $s3_endpoint
            s3-region: $s3_region
            public-base-url: $public_base_url
            s3-timeout-ms: 30000
        dns-client:
            fs-task-processor: fs-task-processor
        testsuite-support:
        server:
            listener:
                port: 8080
                task_processor: main-task-processor
        congestion-control:
            fake-mode: false
            load-enabled: true
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard
        webshot-handler:
            path: /v1/webshot
            method: GET,POST
            task_processor: main-task-processor
            request-timeout-ms: 60000
            max_request_size: &max-data-per-request 65536
        webshots-by-prefix:
            path: /v1/webshot/prefix
            method: GET
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-disallow-and-purge:
            path: /v1/disallow-and-purge
            method: POST
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-by-id:
            path: /v1/webshot/{uuid}
            method: GET
            task_processor: main-task-processor
            request-timeout-ms: 10000
            max_request_size: *max-data-per-request
        webshot-crud:
            webshots-page-max: 2
            crawl-concurrency: *blocking_num_workers
            webshots-per-link-max: 2
            webshots-links-per-page-max: 10
            crawler-network: 'crawler_net'
            crawler-image: 'webrecorder/browsertrix-crawler'
            crawler-workers: 1
            crawler-page-load-timeout-sec: 10
            crawler-post-load-delay-sec: 1
            crawler-net-idle-wait-sec: 0
            crawler-page-extra-delay-sec: 3
            crawler-behavior-timeout-sec: 1
            crawler-overhead-timeout-sec: 45
            purge-job-timeout-sec: 300
            crawler-lang: 'en'
            crawler-scope-type: 'page-spa'
            s3-use-sts: $s3_use_sts
            s3-credentials-endpoint: 'https://sts.yandexcloud.net/'
            s3-credentials-duration-sec: 3600
            s3-credentials-refresh-margin-sec: 300
            s3-credentials-refresh-retry-sec: 60
        webshot-meta-db:
            dbconnection: $pg_webshot_meta_dsn
            blocking_task_processor: fs-task-processor
        denylist-db:
            dbconnection: $pg_denylist_dsn
            blocking_task_processor: fs-task-processor
        webshot-denylist:
