s3_bucket: webshot
s3_endpoint: "https://storage.yandexcloud.net/"
s3_region: "ru-central1"
public_base_url: "https://storage.yandexcloud.net/webshot"
s3_use_sts: true
s3_credentials_endpoint: "https://sts.yandexcloud.net/"
s3_credentials_duration_sec: 3600
s3_credentials_refresh_margin_sec: 300
s3_credentials_refresh_retry_sec: 60
pg_capture_meta_db_dsn: "postgresql://postgres@localhost:5432/webshot_prodlike_capture_meta_db"
pg_shared_state_db_dsn: "postgresql://postgres@localhost:5432/webshot_prodlike_shared_state_db"
crawler_run_timeout_sec: 15
crawler_job_overhead_timeout_sec: 45
link_cooldown_sec: 0
secdist_path: secdist.json
